# Generated by Django 5.0.3 on 2024-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.BigIntegerField()),
                ('about', models.CharField(max_length=2048)),
                ('college_name', models.CharField(max_length=512)),
                ('college_start_year', models.DateField()),
                ('college_end_year', models.DateField()),
                ('college_activity', models.CharField(max_length=1024)),
                ('college_pointers', models.FloatField()),
            ],
        ),
    ]
